<?php


namespace Demo\Core\FlowDesigner\Classes\Beans;


use October\Rain\Exception\ApplicationException;

class Edge extends FlowItem
{
    /**@var string $source id of source node port */
    protected $source;
    /**@var string $target id of target node port */
    protected $target;

    /**
     * @return Port
     */
    public function getTargetPort()
    {
        $edge = $this;
        $node = $this->flow->getNodes()->first(function ($node) use ($edge) {
            return $edge->target === $node->id;
        });
        if (empty($node)) {
            throw new ApplicationException('Enable to parse flow. Invalid definition port with id ' . $edge->target . ' does not exists');
        }
    }

    /**
     * @return Port
     */
    public function getSourcePort()
    {
        $edge = $this;
        return $this->flow->getNodes()->first(function ($node) use ($edge) {
            return $edge->source === $node->id;
        });
    }

    public function unserialize(array $jsonItem)
    {
        parent::unserialize($jsonItem); // TODO: Change the autogenerated stub
        $this->source = $jsonItem['source'];
        $this->target = $jsonItem['target'];
    }
}
