<?php
namespace Demo\Casemanager\Seeds\V0_0;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds casemanager d */
class SeedDemoCoreNavigations implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_navigations')->insert([
            [
                                                                            "id"=>"d2faa680-0546-11eb-93c4-7b5f45e08ebe",
                                                                                        "created_at"=>"2020-10-03 07:05:31",
                                                                                        "updated_at"=>"2020-10-03 07:08:29",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "version"=> 0,
                                                                                        "label"=>"Create",
                                                                                        "icon"=>"oc-icon-medkit",
                                                                                        "type"=>"script",
                                                                                        "active"=> 1,
                                                                                        "name"=>"create-case",
                                                                                        "description"=> "",
                                                                                        "url"=> "",
                                                                                        "model"=> null,
                                                                                        "list"=> "",
                                                                                        "form"=> null,
                                                                                        "view"=> "",
                                                                                        "uipage_id"=> null,
                                                                                        "record_id"=> null,
                                                                                        "dashboard_id"=> null,
                                                                                        "widget_id"=> null,
                                                                                        "engine_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "parent_id"=> null,
                                                                                        "sort_order"=> 4,
                                                                                        "position"=>"topnav",
                                                                                        "script"=>"function () {\r\n    engine.ui.EngineForm.getInstance({\r\n        modelRecord: {\r\n            controller: 'demo/casemanager/casecontroller'\r\n        },\r\n    }).loadFormContent().showInPopup({\r\n        title: 'New Case',\r\n        size: 'xl',\r\n        actions: [{\r\n            label: 'Save',\r\n            handler: function (e, popup) {\r\n                \$.request('onSave', {\r\n                    success: function () {\r\n                        popup.close();\r\n                    }\r\n                })\r\n\r\n            }\r\n        }]\r\n    }).then(function (popup) {\r\n        popup.\$body.find('.page-breadcrumb').hide();\r\n        popup.\$body.find('.form-buttons').hide();\r\n    });\r\n}",
                                                                                        "tooltip"=>"Create New Case",
                                                                                        "nav_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83"
                            ] ,            [
                                                                            "id"=>"01f868fa-2ac6-42c1-b5e0-030df343dd31",
                                                                                        "created_at"=> null,
                                                                                        "updated_at"=>"2020-09-30 04:21:23",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "version"=> 0,
                                                                                        "label"=>"All Cases",
                                                                                        "icon"=>"oc-icon-medkit",
                                                                                        "type"=>"list",
                                                                                        "active"=> 1,
                                                                                        "name"=>"all-cases",
                                                                                        "description"=> "",
                                                                                        "url"=> "",
                                                                                        "model"=>"Demo\Casemanager\Models\CaseModel",
                                                                                        "list"=> "",
                                                                                        "form"=> "",
                                                                                        "view"=> "",
                                                                                        "uipage_id"=> null,
                                                                                        "record_id"=> null,
                                                                                        "dashboard_id"=> null,
                                                                                        "widget_id"=> null,
                                                                                        "engine_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "parent_id"=>"3280cd3c-8a95-4683-b661-7846bc9fdf03",
                                                                                        "sort_order"=> 0,
                                                                                        "position"=>"sidebar",
                                                                                        "script"=> "",
                                                                                        "tooltip"=> "",
                                                                                        "nav_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83"
                            ] ,            [
                                                                            "id"=>"ed44650b-b008-456c-85de-adc1270cfbed",
                                                                                        "created_at"=>"2020-05-10 10:28:19",
                                                                                        "updated_at"=>"2020-05-16 14:59:12",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "version"=> 2,
                                                                                        "label"=>"Youtube",
                                                                                        "icon"=>"oc-icon-adjust",
                                                                                        "type"=>"url",
                                                                                        "active"=> 1,
                                                                                        "name"=>"youtube",
                                                                                        "description"=> "",
                                                                                        "url"=>"https://www.youtube.com/embed/RBumgq5yVrA",
                                                                                        "model"=>"Demo\Report\Models\Dashboard",
                                                                                        "list"=> null,
                                                                                        "form"=> "",
                                                                                        "view"=> null,
                                                                                        "uipage_id"=> null,
                                                                                        "record_id"=> null,
                                                                                        "dashboard_id"=> null,
                                                                                        "widget_id"=> null,
                                                                                        "engine_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "parent_id"=>"3280cd3c-8a95-4683-b661-7846bc9fdf03",
                                                                                        "sort_order"=> 5,
                                                                                        "position"=>"sidebar",
                                                                                        "script"=> null,
                                                                                        "tooltip"=> null,
                                                                                        "nav_application_id"=>"dc81b635-1d0a-4f3e-83af-13642d56abe4"
                            ] ,            [
                                                                            "id"=>"81d30c41-fd09-4757-a6f9-e92463faf8bc",
                                                                                        "created_at"=>"2020-05-13 04:38:17",
                                                                                        "updated_at"=>"2020-06-20 06:33:23",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "version"=> 0,
                                                                                        "label"=>"Dashboard",
                                                                                        "icon"=>"oc-icon-dashboard",
                                                                                        "type"=>"dashboard",
                                                                                        "active"=> 1,
                                                                                        "name"=>"dashboard",
                                                                                        "description"=> "",
                                                                                        "url"=> "",
                                                                                        "model"=> null,
                                                                                        "list"=> null,
                                                                                        "form"=> "",
                                                                                        "view"=> "",
                                                                                        "uipage_id"=> null,
                                                                                        "record_id"=> null,
                                                                                        "dashboard_id"=>"cc326831-e515-44a8-8eb8-b23b8fa8fdaa",
                                                                                        "widget_id"=> null,
                                                                                        "engine_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "parent_id"=>"3280cd3c-8a95-4683-b661-7846bc9fdf03",
                                                                                        "sort_order"=> 4,
                                                                                        "position"=>"sidebar",
                                                                                        "script"=> null,
                                                                                        "tooltip"=> null,
                                                                                        "nav_application_id"=>"dc81b635-1d0a-4f3e-83af-13642d56abe4"
                            ] ,            [
                                                                            "id"=>"c3984be1-820c-4cc8-a675-742815313468",
                                                                                        "created_at"=>"2020-05-18 04:33:41",
                                                                                        "updated_at"=>"2020-07-13 11:25:02",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "version"=> 0,
                                                                                        "label"=>"My Cases",
                                                                                        "icon"=>"oc-icon-briefcase",
                                                                                        "type"=>"list",
                                                                                        "active"=> 1,
                                                                                        "name"=>"my-cases",
                                                                                        "description"=> "",
                                                                                        "url"=> "",
                                                                                        "model"=>"Demo\Casemanager\Models\CaseModel",
                                                                                        "list"=>"\$/demo/casemanager/models/casemodel/my_case_columns.yaml",
                                                                                        "form"=> "",
                                                                                        "view"=> "",
                                                                                        "uipage_id"=> null,
                                                                                        "record_id"=> null,
                                                                                        "dashboard_id"=> null,
                                                                                        "widget_id"=> null,
                                                                                        "engine_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "parent_id"=>"3280cd3c-8a95-4683-b661-7846bc9fdf03",
                                                                                        "sort_order"=> 0,
                                                                                        "position"=>"sidebar",
                                                                                        "script"=> null,
                                                                                        "tooltip"=> null,
                                                                                        "nav_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83"
                            ] ,            [
                                                                            "id"=>"6f85afbb-3858-4387-b4ce-9f70cf19ed20",
                                                                                        "created_at"=>"2020-05-13 04:37:14",
                                                                                        "updated_at"=>"2020-06-14 06:00:06",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "version"=> 0,
                                                                                        "label"=>"Case Report",
                                                                                        "icon"=>"oc-icon-book",
                                                                                        "type"=>"widget",
                                                                                        "active"=> 1,
                                                                                        "name"=>"case-report",
                                                                                        "description"=> "",
                                                                                        "url"=> "",
                                                                                        "model"=> null,
                                                                                        "list"=> null,
                                                                                        "form"=> "",
                                                                                        "view"=> "",
                                                                                        "uipage_id"=> null,
                                                                                        "record_id"=> null,
                                                                                        "dashboard_id"=> null,
                                                                                        "widget_id"=>"84383d11-89c6-4dac-906c-bb2b08923b53",
                                                                                        "engine_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "parent_id"=>"3280cd3c-8a95-4683-b661-7846bc9fdf03",
                                                                                        "sort_order"=> 0,
                                                                                        "position"=>"sidebar",
                                                                                        "script"=> null,
                                                                                        "tooltip"=> null,
                                                                                        "nav_application_id"=>"df07f9b4-26c1-40ca-ba1f-1b77b1692b83"
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_navigations')->where('engine_application_id', 'df07f9b4-26c1-40ca-ba1f-1b77b1692b83')->delete();
            }
}
