<?php
namespace Demo\Workflow\Seeds;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds Demo.Workflow d */
class SeedDemoCorePermissions implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_permissions')->insert([
            [
                                                                            "id"=>"452cba39-4407-44c0-bece-ce0b9e4b3a4b",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\Queue",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queue.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"fef689c6-714c-4410-bfe7-54733227cb9f",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueueItem",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueitem.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Item Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"9df3a2eb-6ce2-4632-af67-2cde68e3d74a",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueueItem",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueitem.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Item Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"2f4128ce-ab18-4658-93b9-9c1e4a54cb79",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueuePopCriteria",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queuepopcriteria.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Pop Criteria Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"d111b49b-eb12-4899-8998-16ac09738ebc",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowState",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowstate.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow State Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"2881207e-0451-4c89-a2a5-86245cfccadc",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\Workflow",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflow.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"49836cad-f197-4e87-94f9-3cbfd27232f1",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowItem",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowitem.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Item Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"5f19ba46-e496-4d19-82ac-46dad3182d8b",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowTransition",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowtransition.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Transition Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"3be5c317-d04e-4f03-8459-76b19e3a2ddd",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueueRoutingRule",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueroutingrule.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Routing Rule Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"fad2b37f-2de6-4eb8-a812-b1bed9df6ff4",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueueRoutingRule",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueroutingrule.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Routing Rule Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"cde32f8a-1898-48e5-89cb-f2947b115d16",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowItem",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowitem.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Item Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"5d476e2d-47e3-48a1-880f-785016d67cdb",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowTransition",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowtransition.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Transition Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"5219b163-6e07-4b61-86b7-82834723edea",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\Queue",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queue.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"176b1eed-69ed-451f-80d5-07fd394e3ea0",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\Workflow",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflow.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"b996fcb5-c7a2-4250-a165-134e566d52a1",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowState",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowstate.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow State Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"77573897-1af7-40bb-b829-9e68884ee031",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowTransition",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowtransition.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Transition Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"e565c9a0-395d-4fb8-801b-d701bd2e3aa4",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\Workflow",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflow.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"2ecfe890-4cb3-4b9b-a735-1b62288bfd78",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\Queue",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queue.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"92a3d261-b3ef-45ad-ad91-71a12096d655",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\Workflow",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflow.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"9b82540a-c92a-4ecd-baa3-0128ca505405",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\Queue",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queue.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"0407e203-77b1-4c10-b485-705ea9751d73",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueueItem",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueitem.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Item Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"3b5d8aac-ebfe-48bf-bb63-907b8316c528",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowItem",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowitem.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Item Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"c0cde7b7-a54f-42fd-b517-2927ad90a5ad",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowState",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowstate.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow State Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"c834feef-1af7-40ca-aca6-fa80fa0cc22b",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueuePopCriteria",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queuepopcriteria.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Pop Criteria Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"2a8c8d75-df52-43eb-8a58-a40d4629455a",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueuePopCriteria",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queuepopcriteria.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Pop Criteria Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"30765ba2-36a4-453c-8046-3ae816e2f983",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowTransition",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowtransition.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Transition Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"973c4985-0676-4842-8dcf-097e14d3977a",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowItem",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowitem.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Item Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"7c6d564b-7ee6-4ff7-ac45-8817a64a9b17",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueuePopCriteria",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queuepopcriteria.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Pop Criteria Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"81cd5035-62f4-477e-99fd-bd3b968b1f2e",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueueRoutingRule",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueroutingrule.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Routing Rule Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"e7e68978-0cb3-49a4-a950-0d67a0d9065a",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueueRoutingRule",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueroutingrule.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Routing Rule Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"4fba7c30-422b-4f71-bfd3-1d522cf1a006",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowState",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowstate.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow State Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"07815934-fa5e-4508-a31c-db669305bb70",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> "8374144e-94a5-470d-8d9e-4cbad05102ad",
                                                                                        "model"=>"Demo\Workflow\Models\QueueItem",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueitem.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Item Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_permissions')->where('plugin_id', 11)->delete();
            }
}
