<?php
namespace Demo\Workflow\Seeds;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds Demo.Workflow d */
class SeedDemoCorePermissions implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_permissions')->insert([
            [
                                                                            "id"=> 211,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\Queue",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queue.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 212,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueueItem",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueitem.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Item Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 213,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueueItem",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueitem.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Item Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 214,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueuePopCriteria",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queuepopcriteria.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Pop Criteria Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 215,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowState",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowstate.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow State Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 216,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\Workflow",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflow.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 250,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowItem",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowitem.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Item Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 217,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowTransition",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowtransition.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Transition Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 251,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueueRoutingRule",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueroutingrule.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Routing Rule Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 218,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueueRoutingRule",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueroutingrule.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Routing Rule Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 253,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowItem",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowitem.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Item Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 219,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowTransition",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowtransition.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Transition Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 220,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\Queue",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queue.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 221,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\Workflow",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflow.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 222,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowState",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowstate.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow State Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 223,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowTransition",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowtransition.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Transition Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 224,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\Workflow",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflow.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 225,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\Queue",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queue.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 226,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\Workflow",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflow.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 227,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\Queue",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queue.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 228,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueueItem",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueitem.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Item Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 229,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowItem",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowitem.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Item Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 230,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowState",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowstate.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow State Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 231,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueuePopCriteria",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queuepopcriteria.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Pop Criteria Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 232,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueuePopCriteria",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queuepopcriteria.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Pop Criteria Write Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 233,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowTransition",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowtransition.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Transition Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 234,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowItem",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowitem.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow Item Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 235,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueuePopCriteria",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queuepopcriteria.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Pop Criteria Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 236,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueueRoutingRule",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueroutingrule.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Routing Rule Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 237,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueueRoutingRule",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueroutingrule.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Routing Rule Delete Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 238,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowState",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.workflowstate.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Workflow State Create Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 239,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 11,
                                                                                        "model"=>"Demo\Workflow\Models\QueueItem",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.workflow::models.queueitem.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Queue Item Read Permission",
                                                                                        "description"=> null,
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_permissions')->where('plugin_id', 11)->delete();
            }
}
