<?php
namespace Demo\Report\Seeds;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds Demo.Report d */
class SeedDemoCoreSecurityPolicies implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_security_policies')->insert([
            [
                                                                            "id"=>"d718666f-f90b-4c8b-8458-373cdc28f7bc",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Widget Security Policy-1",
                                                                                        "description"=>"Security Policy for all operations on Widget",
                                                                                        "plugin_id"=> 14
                            ] ,            [
                                                                            "id"=>"1fcbb601-df64-4947-b1ca-e277326b5ef0",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-28 14:43:57",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Dashboard Security Policy-1",
                                                                                        "description"=>"Security Policy for all operations on Dashboard",
                                                                                        "plugin_id"=> 14
                            ] ,            [
                                                                            "id"=>"1bb91fca-e15a-4fb7-b176-0be599769c86",
                                                                                        "created_at"=>"2020-05-29 08:12:46",
                                                                                        "updated_at"=>"2020-05-29 08:12:46",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Service Channel Policy",
                                                                                        "description"=>"Autogenerated policy for Service Channel",
                                                                                        "plugin_id"=> 14
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_security_policies')->where('plugin_id', 14)->delete();
            }
}
