<?php

namespace Demo\Core\Seeds;

use Demo\Core\Models\ModelModel;
use Schema;
use Seeder;
use Db;

class BuilderTableSeedDemoCorePermission extends Seeder
{
    /*select row_number() OVER () as id,
    model.model_type as model,
    model.plugin_id,
    model.created_at,
    model.updated_at,
    model.created_by_id,
    model.updated_by_id,
    'delete' as operation,
    true as active,
    true as system,
    concat(model.name,' Delete Permission') as name,
    concat(lower(plugin.code),'::',replace(lower(substr(replace(model.model_type,replace(plugin.code,'.','\'),''),2)),'\','.'),'.row.delete') as code
    from demo_core_models model
           join system_plugin_versions plugin on plugin.id = model.plugin_id;


    delete from demo_core_models where plugin_id = 10;
    delete from demo_core_permissions;
    delete from demo_core_model_associations where plugin_id = 10;*/
    public function run()
    {
        Db::table('demo_core_permissions')->insert([
            [
                'id' => 1,
                'model' => 'Demo\Workflow\Models\Queue',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Queue Read Permission',
                'code' => 'demo.workflow::models.queue.row.read'
            ],
            [
                'id' => 2,
                'model' => 'Demo\Workflow\Models\QueueItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Queue Item Read Permission',
                'code' => 'demo.workflow::models.queueitem.row.read'
            ],
            [
                'id' => 3,
                'model' => 'Demo\Workflow\Models\QueuePopCriteria',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Queue Pop Criteria Read Permission',
                'code' => 'demo.workflow::models.queuepopcriteria.row.read'
            ],
            [
                'id' => 4,
                'model' => 'Demo\Workflow\Models\QueueRoutingRule',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Queue Routing Rule Read Permission',
                'code' => 'demo.workflow::models.queueroutingrule.row.read'
            ],
            [
                'id' => 5,
                'model' => 'Demo\Workflow\Models\Workflow',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Read Permission',
                'code' => 'demo.workflow::models.workflow.row.read'
            ],
            [
                'id' => 6,
                'model' => 'Demo\Workflow\Models\WorkflowItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Item Read Permission',
                'code' => 'demo.workflow::models.workflowitem.row.read'
            ],
            [
                'id' => 7,
                'model' => 'Demo\Workflow\Models\WorkflowState',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Workflow State Read Permission',
                'code' => 'demo.workflow::models.workflowstate.row.read'
            ],
            [
                'id' => 8,
                'model' => 'Demo\Workflow\Models\WorkflowTransition',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Transition Read Permission',
                'code' => 'demo.workflow::models.workflowtransition.row.read'
            ],
            [
                'id' => 9,
                'model' => 'Demo\Workflow\Models\Webhook',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Read Permission',
                'code' => 'demo.workflow::models.webhook.row.read'
            ],
            [
                'id' => 10,
                'model' => 'Demo\Workflow\Models\Queue',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Queue Read Permission',
                'code' => 'demo.workflow::models.queue.row.read'
            ],
            [
                'id' => 11,
                'model' => 'Demo\Workflow\Models\QueueItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Queue Item Read Permission',
                'code' => 'demo.workflow::models.queueitem.row.read'
            ],
            [
                'id' => 12,
                'model' => 'Demo\Workflow\Models\QueuePopCriteria',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Queue Pop Criteria Read Permission',
                'code' => 'demo.workflow::models.queuepopcriteria.row.read'
            ],
            [
                'id' => 13,
                'model' => 'Demo\Workflow\Models\QueueRoutingRule',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Queue Routing Rule Read Permission',
                'code' => 'demo.workflow::models.queueroutingrule.row.read'
            ],
            [
                'id' => 14,
                'model' => 'Demo\Workflow\Models\Workflow',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Read Permission',
                'code' => 'demo.workflow::models.workflow.row.read'
            ],
            [
                'id' => 15,
                'model' => 'Demo\Workflow\Models\WorkflowItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Item Read Permission',
                'code' => 'demo.workflow::models.workflowitem.row.read'
            ],
            [
                'id' => 16,
                'model' => 'Demo\Workflow\Models\WorkflowState',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Workflow State Read Permission',
                'code' => 'demo.workflow::models.workflowstate.row.read'
            ],
            [
                'id' => 17,
                'model' => 'Demo\Workflow\Models\WorkflowTransition',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Transition Read Permission',
                'code' => 'demo.workflow::models.workflowtransition.row.read'
            ],
            [
                'id' => 18,
                'model' => 'Demo\Workflow\Models\Webhook',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Read Permission',
                'code' => 'demo.workflow::models.webhook.row.read'
            ],
            [
                'id' => 19,
                'model' => 'Demo\Core\Models\ModelModel',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Models Model Read Permission',
                'code' => 'demo.core::models.model.row.read'
            ],
            [
                'id' => 20,
                'model' => 'Demo\Core\Models\CustomField',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Custom Field Read Permission',
                'code' => 'demo.core::models.customfield.row.read'
            ],
            [
                'id' => 21,
                'model' => 'Demo\Core\Models\FormField',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Form Field Read Permission',
                'code' => 'demo.core::models.formfield.row.read'
            ],
            [
                'id' => 22,
                'model' => 'Demo\Core\Models\EventHandler',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Event Handler Read Permission',
                'code' => 'demo.core::models.eventhandler.row.read'
            ],
            [
                'id' => 23,
                'model' => 'Demo\Core\Models\InboundApi',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Inbound Api Read Permission',
                'code' => 'demo.core::models.inboundapi.row.read'
            ],
            [
                'id' => 24,
                'model' => 'Demo\Core\Models\Command',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Command Read Permission',
                'code' => 'demo.core::models.command.row.read'
            ],
            [
                'id' => 25,
                'model' => 'Demo\Core\Models\Iframe',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Iframe Read Permission',
                'code' => 'demo.core::models.iframe.row.read'
            ],
            [
                'id' => 26,
                'model' => 'Demo\Core\Models\JavascriptLibrary',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Javascript Library Read Permission',
                'code' => 'demo.core::models.javascriptlibrary.row.read'
            ],
            [
                'id' => 27,
                'model' => 'Demo\Core\Models\Webhook',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Read Permission',
                'code' => 'demo.core::models.webhook.row.read'
            ],
            [
                'id' => 28,
                'model' => 'Demo\Core\Models\ModelAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Model Association Read Permission',
                'code' => 'demo.core::models.modelassociation.row.read'
            ],
            [
                'id' => 29,
                'model' => 'Demo\Core\Models\Role',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Role Read Permission',
                'code' => 'demo.core::models.role.row.read'
            ],
            [
                'id' => 30,
                'model' => 'Demo\Core\Models\Permission',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Permission Read Permission',
                'code' => 'demo.core::models.permission.row.read'
            ],
            [
                'id' => 31,
                'model' => 'Demo\Core\Models\SecurityPolicy',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Security Policy Read Permission',
                'code' => 'demo.core::models.securitypolicy.row.read'
            ],
            [
                'id' => 32,
                'model' => 'Demo\Core\Models\PermissionPolicyAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Security Policy Association Read Permission',
                'code' => 'demo.core::models.permissionpolicyassociation.row.read'
            ],
            [
                'id' => 33,
                'model' => 'Demo\Core\Models\RolePolicyAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Role Policy Association Read Permission',
                'code' => 'demo.core::models.rolepolicyassociation.row.read'
            ],
            [
                'id' => 34,
                'model' => 'Demo\Core\Models\CoreUser',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'User Read Permission',
                'code' => 'demo.core::models.coreuser.row.read'
            ],
            [
                'id' => 35,
                'model' => 'Demo\Core\Models\CoreUserGroup',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'User Read Permission',
                'code' => 'demo.core::models.coreusergroup.row.read'
            ],
            [
                'id' => 36,
                'model' => 'Demo\Report\Models\Widget',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Widget Read Permission',
                'code' => 'demo.report::models.widget.row.read'
            ],
            [
                'id' => 37,
                'model' => 'Demo\Report\Models\Dashboard',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Dashboard Read Permission',
                'code' => 'demo.report::models.dashboard.row.read'
            ], [
                'id' => 41,
                'model' => 'Demo\Workflow\Models\Queue',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Queue Write Permission',
                'code' => 'demo.workflow::models.queue.row.write'
            ],
            [
                'id' => 42,
                'model' => 'Demo\Workflow\Models\QueueItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Queue Item Write Permission',
                'code' => 'demo.workflow::models.queueitem.row.write'
            ],
            [
                'id' => 43,
                'model' => 'Demo\Workflow\Models\QueuePopCriteria',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Queue Pop Criteria Write Permission',
                'code' => 'demo.workflow::models.queuepopcriteria.row.write'
            ],
            [
                'id' => 44,
                'model' => 'Demo\Workflow\Models\QueueRoutingRule',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Queue Routing Rule Write Permission',
                'code' => 'demo.workflow::models.queueroutingrule.row.write'
            ],
            [
                'id' => 45,
                'model' => 'Demo\Workflow\Models\Workflow',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Write Permission',
                'code' => 'demo.workflow::models.workflow.row.write'
            ],
            [
                'id' => 46,
                'model' => 'Demo\Workflow\Models\WorkflowItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Item Write Permission',
                'code' => 'demo.workflow::models.workflowitem.row.write'
            ],
            [
                'id' => 47,
                'model' => 'Demo\Workflow\Models\WorkflowState',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Workflow State Write Permission',
                'code' => 'demo.workflow::models.workflowstate.row.write'
            ],
            [
                'id' => 48,
                'model' => 'Demo\Workflow\Models\WorkflowTransition',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Transition Write Permission',
                'code' => 'demo.workflow::models.workflowtransition.row.write'
            ],
            [
                'id' => 49,
                'model' => 'Demo\Workflow\Models\Webhook',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Write Permission',
                'code' => 'demo.workflow::models.webhook.row.write'
            ],
            [
                'id' => 50,
                'model' => 'Demo\Workflow\Models\Queue',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Queue Write Permission',
                'code' => 'demo.workflow::models.queue.row.write'
            ],
            [
                'id' => 51,
                'model' => 'Demo\Workflow\Models\QueueItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Queue Item Write Permission',
                'code' => 'demo.workflow::models.queueitem.row.write'
            ],
            [
                'id' => 52,
                'model' => 'Demo\Workflow\Models\QueuePopCriteria',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Queue Pop Criteria Write Permission',
                'code' => 'demo.workflow::models.queuepopcriteria.row.write'
            ],
            [
                'id' => 53,
                'model' => 'Demo\Workflow\Models\QueueRoutingRule',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Queue Routing Rule Write Permission',
                'code' => 'demo.workflow::models.queueroutingrule.row.write'
            ],
            [
                'id' => 54,
                'model' => 'Demo\Workflow\Models\Workflow',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Write Permission',
                'code' => 'demo.workflow::models.workflow.row.write'
            ],
            [
                'id' => 55,
                'model' => 'Demo\Workflow\Models\WorkflowItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Item Write Permission',
                'code' => 'demo.workflow::models.workflowitem.row.write'
            ],
            [
                'id' => 56,
                'model' => 'Demo\Workflow\Models\WorkflowState',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Workflow State Write Permission',
                'code' => 'demo.workflow::models.workflowstate.row.write'
            ],
            [
                'id' => 57,
                'model' => 'Demo\Workflow\Models\WorkflowTransition',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Transition Write Permission',
                'code' => 'demo.workflow::models.workflowtransition.row.write'
            ],
            [
                'id' => 58,
                'model' => 'Demo\Workflow\Models\Webhook',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Write Permission',
                'code' => 'demo.workflow::models.webhook.row.write'
            ],
            [
                'id' => 59,
                'model' => 'Demo\Core\Models\ModelModel',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Models Model Write Permission',
                'code' => 'demo.core::models.model.row.write'
            ],
            [
                'id' => 60,
                'model' => 'Demo\Core\Models\CustomField',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Custom Field Write Permission',
                'code' => 'demo.core::models.customfield.row.write'
            ],
            [
                'id' => 61,
                'model' => 'Demo\Core\Models\FormField',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Form Field Write Permission',
                'code' => 'demo.core::models.formfield.row.write'
            ],
            [
                'id' => 62,
                'model' => 'Demo\Core\Models\EventHandler',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Event Handler Write Permission',
                'code' => 'demo.core::models.eventhandler.row.write'
            ],
            [
                'id' => 63,
                'model' => 'Demo\Core\Models\InboundApi',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Inbound Api Write Permission',
                'code' => 'demo.core::models.inboundapi.row.write'
            ],
            [
                'id' => 64,
                'model' => 'Demo\Core\Models\Command',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Command Write Permission',
                'code' => 'demo.core::models.command.row.write'
            ],
            [
                'id' => 65,
                'model' => 'Demo\Core\Models\Iframe',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Iframe Write Permission',
                'code' => 'demo.core::models.iframe.row.write'
            ],
            [
                'id' => 66,
                'model' => 'Demo\Core\Models\JavascriptLibrary',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Javascript Library Write Permission',
                'code' => 'demo.core::models.javascriptlibrary.row.write'
            ],
            [
                'id' => 67,
                'model' => 'Demo\Core\Models\Webhook',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Write Permission',
                'code' => 'demo.core::models.webhook.row.write'
            ],
            [
                'id' => 68,
                'model' => 'Demo\Core\Models\ModelAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Model Association Write Permission',
                'code' => 'demo.core::models.modelassociation.row.write'
            ],
            [
                'id' => 69,
                'model' => 'Demo\Core\Models\Role',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Role Write Permission',
                'code' => 'demo.core::models.role.row.write'
            ],
            [
                'id' => 70,
                'model' => 'Demo\Core\Models\Permission',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Permission Write Permission',
                'code' => 'demo.core::models.permission.row.write'
            ],
            [
                'id' => 71,
                'model' => 'Demo\Core\Models\SecurityPolicy',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Security Policy Write Permission',
                'code' => 'demo.core::models.securitypolicy.row.write'
            ],
            [
                'id' => 72,
                'model' => 'Demo\Core\Models\PermissionPolicyAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Security Policy Association Write Permission',
                'code' => 'demo.core::models.permissionpolicyassociation.row.write'
            ],
            [
                'id' => 73,
                'model' => 'Demo\Core\Models\RolePolicyAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Role Policy Association Write Permission',
                'code' => 'demo.core::models.rolepolicyassociation.row.write'
            ],
            [
                'id' => 74,
                'model' => 'Demo\Core\Models\CoreUser',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'User Write Permission',
                'code' => 'demo.core::models.coreuser.row.write'
            ],
            [
                'id' => 75,
                'model' => 'Demo\Core\Models\CoreUserGroup',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'User Write Permission',
                'code' => 'demo.core::models.coreusergroup.row.write'
            ],
            [
                'id' => 76,
                'model' => 'Demo\Report\Models\Widget',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Widget Write Permission',
                'code' => 'demo.report::models.widget.row.write'
            ],
            [
                'id' => 77,
                'model' => 'Demo\Report\Models\Dashboard',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Dashboard Write Permission',
                'code' => 'demo.report::models.dashboard.row.write'
            ], [
                'id' => 81,
                'model' => 'Demo\Workflow\Models\Queue',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Queue Create Permission',
                'code' => 'demo.workflow::models.queue.row.create'
            ],
            [
                'id' => 82,
                'model' => 'Demo\Workflow\Models\QueueItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Queue Item Create Permission',
                'code' => 'demo.workflow::models.queueitem.row.create'
            ],
            [
                'id' => 83,
                'model' => 'Demo\Workflow\Models\QueuePopCriteria',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Queue Pop Criteria Create Permission',
                'code' => 'demo.workflow::models.queuepopcriteria.row.create'
            ],
            [
                'id' => 84,
                'model' => 'Demo\Workflow\Models\QueueRoutingRule',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Queue Routing Rule Create Permission',
                'code' => 'demo.workflow::models.queueroutingrule.row.create'
            ],
            [
                'id' => 85,
                'model' => 'Demo\Workflow\Models\Workflow',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Create Permission',
                'code' => 'demo.workflow::models.workflow.row.create'
            ],
            [
                'id' => 86,
                'model' => 'Demo\Workflow\Models\WorkflowItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Item Create Permission',
                'code' => 'demo.workflow::models.workflowitem.row.create'
            ],
            [
                'id' => 87,
                'model' => 'Demo\Workflow\Models\WorkflowState',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Workflow State Create Permission',
                'code' => 'demo.workflow::models.workflowstate.row.create'
            ],
            [
                'id' => 88,
                'model' => 'Demo\Workflow\Models\WorkflowTransition',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Transition Create Permission',
                'code' => 'demo.workflow::models.workflowtransition.row.create'
            ],
            [
                'id' => 89,
                'model' => 'Demo\Workflow\Models\Webhook',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Create Permission',
                'code' => 'demo.workflow::models.webhook.row.create'
            ],
            [
                'id' => 90,
                'model' => 'Demo\Workflow\Models\Queue',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Queue Create Permission',
                'code' => 'demo.workflow::models.queue.row.create'
            ],
            [
                'id' => 91,
                'model' => 'Demo\Workflow\Models\QueueItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Queue Item Create Permission',
                'code' => 'demo.workflow::models.queueitem.row.create'
            ],
            [
                'id' => 92,
                'model' => 'Demo\Workflow\Models\QueuePopCriteria',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Queue Pop Criteria Create Permission',
                'code' => 'demo.workflow::models.queuepopcriteria.row.create'
            ],
            [
                'id' => 93,
                'model' => 'Demo\Workflow\Models\QueueRoutingRule',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Queue Routing Rule Create Permission',
                'code' => 'demo.workflow::models.queueroutingrule.row.create'
            ],
            [
                'id' => 94,
                'model' => 'Demo\Workflow\Models\Workflow',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Create Permission',
                'code' => 'demo.workflow::models.workflow.row.create'
            ],
            [
                'id' => 95,
                'model' => 'Demo\Workflow\Models\WorkflowItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Item Create Permission',
                'code' => 'demo.workflow::models.workflowitem.row.create'
            ],
            [
                'id' => 96,
                'model' => 'Demo\Workflow\Models\WorkflowState',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Workflow State Create Permission',
                'code' => 'demo.workflow::models.workflowstate.row.create'
            ],
            [
                'id' => 97,
                'model' => 'Demo\Workflow\Models\WorkflowTransition',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Transition Create Permission',
                'code' => 'demo.workflow::models.workflowtransition.row.create'
            ],
            [
                'id' => 98,
                'model' => 'Demo\Workflow\Models\Webhook',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Create Permission',
                'code' => 'demo.workflow::models.webhook.row.create'
            ],
            [
                'id' => 99,
                'model' => 'Demo\Core\Models\ModelModel',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Models Model Create Permission',
                'code' => 'demo.core::models.model.row.create'
            ],
            [
                'id' => 100,
                'model' => 'Demo\Core\Models\CustomField',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Custom Field Create Permission',
                'code' => 'demo.core::models.customfield.row.create'
            ],
            [
                'id' => 101,
                'model' => 'Demo\Core\Models\FormField',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Form Field Create Permission',
                'code' => 'demo.core::models.formfield.row.create'
            ],
            [
                'id' => 102,
                'model' => 'Demo\Core\Models\EventHandler',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Event Handler Create Permission',
                'code' => 'demo.core::models.eventhandler.row.create'
            ],
            [
                'id' => 103,
                'model' => 'Demo\Core\Models\InboundApi',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Inbound Api Create Permission',
                'code' => 'demo.core::models.inboundapi.row.create'
            ],
            [
                'id' => 104,
                'model' => 'Demo\Core\Models\Command',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Command Create Permission',
                'code' => 'demo.core::models.command.row.create'
            ],
            [
                'id' => 105,
                'model' => 'Demo\Core\Models\Iframe',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Iframe Create Permission',
                'code' => 'demo.core::models.iframe.row.create'
            ],
            [
                'id' => 106,
                'model' => 'Demo\Core\Models\JavascriptLibrary',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Javascript Library Create Permission',
                'code' => 'demo.core::models.javascriptlibrary.row.create'
            ],
            [
                'id' => 107,
                'model' => 'Demo\Core\Models\Webhook',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Create Permission',
                'code' => 'demo.core::models.webhook.row.create'
            ],
            [
                'id' => 108,
                'model' => 'Demo\Core\Models\ModelAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Model Association Create Permission',
                'code' => 'demo.core::models.modelassociation.row.create'
            ],
            [
                'id' => 109,
                'model' => 'Demo\Core\Models\Role',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Role Create Permission',
                'code' => 'demo.core::models.role.row.create'
            ],
            [
                'id' => 110,
                'model' => 'Demo\Core\Models\Permission',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Permission Create Permission',
                'code' => 'demo.core::models.permission.row.create'
            ],
            [
                'id' => 111,
                'model' => 'Demo\Core\Models\SecurityPolicy',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Security Policy Create Permission',
                'code' => 'demo.core::models.securitypolicy.row.create'
            ],
            [
                'id' => 112,
                'model' => 'Demo\Core\Models\PermissionPolicyAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Security Policy Association Create Permission',
                'code' => 'demo.core::models.permissionpolicyassociation.row.create'
            ],
            [
                'id' => 113,
                'model' => 'Demo\Core\Models\RolePolicyAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Role Policy Association Create Permission',
                'code' => 'demo.core::models.rolepolicyassociation.row.create'
            ],
            [
                'id' => 114,
                'model' => 'Demo\Core\Models\CoreUser',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'User Create Permission',
                'code' => 'demo.core::models.coreuser.row.create'
            ],
            [
                'id' => 115,
                'model' => 'Demo\Core\Models\CoreUserGroup',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'User Create Permission',
                'code' => 'demo.core::models.coreusergroup.row.create'
            ],
            [
                'id' => 116,
                'model' => 'Demo\Report\Models\Widget',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Widget Create Permission',
                'code' => 'demo.report::models.widget.row.create'
            ],
            [
                'id' => 117,
                'model' => 'Demo\Report\Models\Dashboard',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Dashboard Create Permission',
                'code' => 'demo.report::models.dashboard.row.create'
            ], [
                'id' => 121,
                'model' => 'Demo\Workflow\Models\Queue',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Queue Delete Permission',
                'code' => 'demo.workflow::models.queue.row.delete'
            ],
            [
                'id' => 122,
                'model' => 'Demo\Workflow\Models\QueueItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Queue Item Delete Permission',
                'code' => 'demo.workflow::models.queueitem.row.delete'
            ],
            [
                'id' => 123,
                'model' => 'Demo\Workflow\Models\QueuePopCriteria',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Queue Pop Criteria Delete Permission',
                'code' => 'demo.workflow::models.queuepopcriteria.row.delete'
            ],
            [
                'id' => 124,
                'model' => 'Demo\Workflow\Models\QueueRoutingRule',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Queue Routing Rule Delete Permission',
                'code' => 'demo.workflow::models.queueroutingrule.row.delete'
            ],
            [
                'id' => 125,
                'model' => 'Demo\Workflow\Models\Workflow',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Delete Permission',
                'code' => 'demo.workflow::models.workflow.row.delete'
            ],
            [
                'id' => 126,
                'model' => 'Demo\Workflow\Models\WorkflowItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Item Delete Permission',
                'code' => 'demo.workflow::models.workflowitem.row.delete'
            ],
            [
                'id' => 127,
                'model' => 'Demo\Workflow\Models\WorkflowState',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Workflow State Delete Permission',
                'code' => 'demo.workflow::models.workflowstate.row.delete'
            ],
            [
                'id' => 128,
                'model' => 'Demo\Workflow\Models\WorkflowTransition',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Transition Delete Permission',
                'code' => 'demo.workflow::models.workflowtransition.row.delete'
            ],
            [
                'id' => 129,
                'model' => 'Demo\Workflow\Models\Webhook',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Delete Permission',
                'code' => 'demo.workflow::models.webhook.row.delete'
            ],
            [
                'id' => 130,
                'model' => 'Demo\Workflow\Models\Queue',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Queue Delete Permission',
                'code' => 'demo.workflow::models.queue.row.delete'
            ],
            [
                'id' => 131,
                'model' => 'Demo\Workflow\Models\QueueItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Queue Item Delete Permission',
                'code' => 'demo.workflow::models.queueitem.row.delete'
            ],
            [
                'id' => 132,
                'model' => 'Demo\Workflow\Models\QueuePopCriteria',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Queue Pop Criteria Delete Permission',
                'code' => 'demo.workflow::models.queuepopcriteria.row.delete'
            ],
            [
                'id' => 133,
                'model' => 'Demo\Workflow\Models\QueueRoutingRule',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Queue Routing Rule Delete Permission',
                'code' => 'demo.workflow::models.queueroutingrule.row.delete'
            ],
            [
                'id' => 134,
                'model' => 'Demo\Workflow\Models\Workflow',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Delete Permission',
                'code' => 'demo.workflow::models.workflow.row.delete'
            ],
            [
                'id' => 135,
                'model' => 'Demo\Workflow\Models\WorkflowItem',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Item Delete Permission',
                'code' => 'demo.workflow::models.workflowitem.row.delete'
            ],
            [
                'id' => 136,
                'model' => 'Demo\Workflow\Models\WorkflowState',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Workflow State Delete Permission',
                'code' => 'demo.workflow::models.workflowstate.row.delete'
            ],
            [
                'id' => 137,
                'model' => 'Demo\Workflow\Models\WorkflowTransition',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Workflow Transition Delete Permission',
                'code' => 'demo.workflow::models.workflowtransition.row.delete'
            ],
            [
                'id' => 138,
                'model' => 'Demo\Workflow\Models\Webhook',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Delete Permission',
                'code' => 'demo.workflow::models.webhook.row.delete'
            ],
            [
                'id' => 139,
                'model' => 'Demo\Core\Models\ModelModel',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Models Model Delete Permission',
                'code' => 'demo.core::models.model.row.delete'
            ],
            [
                'id' => 140,
                'model' => 'Demo\Core\Models\CustomField',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Custom Field Delete Permission',
                'code' => 'demo.core::models.customfield.row.delete'
            ],
            [
                'id' => 141,
                'model' => 'Demo\Core\Models\FormField',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Form Field Delete Permission',
                'code' => 'demo.core::models.formfield.row.delete'
            ],
            [
                'id' => 142,
                'model' => 'Demo\Core\Models\EventHandler',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Event Handler Delete Permission',
                'code' => 'demo.core::models.eventhandler.row.delete'
            ],
            [
                'id' => 143,
                'model' => 'Demo\Core\Models\InboundApi',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Inbound Api Delete Permission',
                'code' => 'demo.core::models.inboundapi.row.delete'
            ],
            [
                'id' => 144,
                'model' => 'Demo\Core\Models\Command',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Command Delete Permission',
                'code' => 'demo.core::models.command.row.delete'
            ],
            [
                'id' => 145,
                'model' => 'Demo\Core\Models\Iframe',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Iframe Delete Permission',
                'code' => 'demo.core::models.iframe.row.delete'
            ],
            [
                'id' => 146,
                'model' => 'Demo\Core\Models\JavascriptLibrary',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Javascript Library Delete Permission',
                'code' => 'demo.core::models.javascriptlibrary.row.delete'
            ],
            [
                'id' => 147,
                'model' => 'Demo\Core\Models\Webhook',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Webhook Delete Permission',
                'code' => 'demo.core::models.webhook.row.delete'
            ],
            [
                'id' => 148,
                'model' => 'Demo\Core\Models\ModelAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Model Association Delete Permission',
                'code' => 'demo.core::models.modelassociation.row.delete'
            ],
            [
                'id' => 149,
                'model' => 'Demo\Core\Models\Role',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Role Delete Permission',
                'code' => 'demo.core::models.role.row.delete'
            ],
            [
                'id' => 150,
                'model' => 'Demo\Core\Models\Permission',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Permission Delete Permission',
                'code' => 'demo.core::models.permission.row.delete'
            ],
            [
                'id' => 151,
                'model' => 'Demo\Core\Models\SecurityPolicy',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Security Policy Delete Permission',
                'code' => 'demo.core::models.securitypolicy.row.delete'
            ],
            [
                'id' => 152,
                'model' => 'Demo\Core\Models\PermissionPolicyAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Security Policy Association Delete Permission',
                'code' => 'demo.core::models.permissionpolicyassociation.row.delete'
            ],
            [
                'id' => 153,
                'model' => 'Demo\Core\Models\RolePolicyAssociation',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Role Policy Association Delete Permission',
                'code' => 'demo.core::models.rolepolicyassociation.row.delete'
            ],
            [
                'id' => 154,
                'model' => 'Demo\Core\Models\CoreUser',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'User Delete Permission',
                'code' => 'demo.core::models.coreuser.row.delete'
            ],
            [
                'id' => 155,
                'model' => 'Demo\Core\Models\CoreUserGroup',
                'plugin_id' => 10,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'User Delete Permission',
                'code' => 'demo.core::models.coreusergroup.row.delete'
            ],
            [
                'id' => 156,
                'model' => 'Demo\Report\Models\Widget',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-20 14:15:39',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Widget Delete Permission',
                'code' => 'demo.report::models.widget.row.delete'
            ],
            [
                'id' => 157,
                'model' => 'Demo\Report\Models\Dashboard',
                'plugin_id' => 11,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Dashboard Delete Permission',
                'code' => 'demo.report::models.dashboard.row.delete'
            ], [
                'id' => 158,
                'model' => 'Demo\Notification\Models\NotificationChannel',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Notification Channel Read Permission',
                'code' => 'demo.notification::models.notificationchannel.row.read'
            ], [
                'id' => 159,
                'model' => 'Demo\Notification\Models\NotificationChannel',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Notification Channel Write Permission',
                'code' => 'demo.notification::models.notificationchannel.row.write'
            ], [
                'id' => 160,
                'model' => 'Demo\Notification\Models\NotificationChannel',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Notification Channel Create Permission',
                'code' => 'demo.notification::models.notificationchannel.row.create'
            ], [
                'id' => 161,
                'model' => 'Demo\Notification\Models\NotificationChannel',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Notification Channel Delete Permission',
                'code' => 'demo.notification::models.notificationchannel.row.delete'
            ], [
                'id' => 162,
                'model' => 'Demo\Notification\Models\Notification',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'Notification Read Permission',
                'code' => 'demo.notification::models.notification.row.delete'
            ], [
                'id' => 163,
                'model' => 'Demo\Notification\Models\Notification',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'Notification Write Permission',
                'code' => 'demo.notification::models.notification.row.write'
            ], [
                'id' => 164,
                'model' => 'Demo\Notification\Models\Notification',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'Notification Create Permission',
                'code' => 'demo.notification::models.notification.row.create'
            ], [
                'id' => 165,
                'model' => 'Demo\Notification\Models\Notification',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'Notification Delete Permission',
                'code' => 'demo.notification::models.notification.row.delete'
            ], [
                'id' => 166,
                'model' => 'Demo\Notification\Models\NotificationSubscriber',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'read',
                'active' => true,
                'system' => true,
                'name' => 'NotificationSubscriber Read Permission',
                'code' => 'demo.notification::models.notificationsubscriber.row.delete'
            ], [
                'id' => 167,
                'model' => 'Demo\Notification\Models\NotificationSubscriber',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'write',
                'active' => true,
                'system' => true,
                'name' => 'NotificationSubscriber Write Permission',
                'code' => 'demo.notification::models.notificationsubscriber.row.write'
            ], [
                'id' => 168,
                'model' => 'Demo\Notification\Models\NotificationSubscriber',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'create',
                'active' => true,
                'system' => true,
                'name' => 'NotificationSubscriber Create Permission',
                'code' => 'demo.notification::models.notificationsubscriber.row.create'
            ], [
                'id' => 169,
                'model' => 'Demo\Notification\Models\NotificationSubscriber',
                'plugin_id' => 15,
                'created_at' => '2019-12-20 14:15:39',
                'updated_at' => '2019-12-28 14:43:57',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'operation' => 'delete',
                'active' => true,
                'system' => true,
                'name' => 'NotificationSubscriber Delete Permission',
                'code' => 'demo.notification::models.notificationsubscriber.row.delete'
            ]

        ]);
    }
}
