<?php

namespace Demo\Core\Seeds;

use Demo\Core\Models\ModelModel;
use Schema;
use Seeder;
use Db;
use Demo\Core\Classes\Ifs\Seedable;

class BuilderTableSeedDemoCorePermission implements Seedable
{
    /*select row_number() OVER () as id,
    model.model_type as model,
    model.plugin_id,
    model.created_at,
    model.updated_at,
    model.created_by_id,
    model.updated_by_id,
    'delete' as operation,
    true as active,
    true as system,
    concat(model.name,' Delete Permission') as name,
    concat(lower(plugin.code),'::',replace(lower(substr(replace(model.model_type,replace(plugin.code,'.','\'),''),2)),'\','.'),'.row.delete') as code
    from demo_core_models model
           join system_plugin_versions plugin on plugin.id = model.plugin_id;


    delete from demo_core_models where plugin_id = 10;
    delete from demo_core_permissions;
    delete from demo_core_model_associations where plugin_id = 10;*/
    public function install()
    {
        Db::table('demo_core_permissions')->insert(json_decode('[
  {
    "id": 19,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\ModelModel",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.model.row.read",
    "name": "Models Model Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 20,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CustomField",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.customfield.row.read",
    "name": "Custom Field Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 21,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\FormField",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.formfield.row.read",
    "name": "Form Field Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 22,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\EventHandler",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.eventhandler.row.read",
    "name": "Event Handler Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 23,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\InboundApi",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.inboundapi.row.read",
    "name": "Inbound Api Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 24,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Command",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.command.row.read",
    "name": "Command Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 25,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Iframe",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.iframe.row.read",
    "name": "Iframe Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 26,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\JavascriptLibrary",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.javascriptlibrary.row.read",
    "name": "Javascript Library Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 27,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Webhook",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.webhook.row.read",
    "name": "Webhook Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 28,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\ModelAssociation",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.modelassociation.row.read",
    "name": "Model Association Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 29,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Role",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.role.row.read",
    "name": "Role Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 30,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Permission",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.permission.row.read",
    "name": "Permission Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 31,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\SecurityPolicy",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.securitypolicy.row.read",
    "name": "Security Policy Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 32,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\PermissionPolicyAssociation",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.permissionpolicyassociation.row.read",
    "name": "Security Policy Association Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 33,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\RolePolicyAssociation",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.rolepolicyassociation.row.read",
    "name": "Role Policy Association Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 34,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CoreUser",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.coreuser.row.read",
    "name": "User Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 35,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CoreUserGroup",
    "operation": "read",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.coreusergroup.row.read",
    "name": "User Read Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 59,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\ModelModel",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.model.row.write",
    "name": "Models Model Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 60,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CustomField",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.customfield.row.write",
    "name": "Custom Field Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 61,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\FormField",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.formfield.row.write",
    "name": "Form Field Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 62,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\EventHandler",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.eventhandler.row.write",
    "name": "Event Handler Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 63,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\InboundApi",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.inboundapi.row.write",
    "name": "Inbound Api Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 64,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Command",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.command.row.write",
    "name": "Command Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 65,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Iframe",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.iframe.row.write",
    "name": "Iframe Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 66,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\JavascriptLibrary",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.javascriptlibrary.row.write",
    "name": "Javascript Library Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 67,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Webhook",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.webhook.row.write",
    "name": "Webhook Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 68,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\ModelAssociation",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.modelassociation.row.write",
    "name": "Model Association Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 69,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Role",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.role.row.write",
    "name": "Role Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 70,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Permission",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.permission.row.write",
    "name": "Permission Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 71,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\SecurityPolicy",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.securitypolicy.row.write",
    "name": "Security Policy Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 72,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\PermissionPolicyAssociation",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.permissionpolicyassociation.row.write",
    "name": "Security Policy Association Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 73,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\RolePolicyAssociation",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.rolepolicyassociation.row.write",
    "name": "Role Policy Association Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 74,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CoreUser",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.coreuser.row.write",
    "name": "User Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 75,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CoreUserGroup",
    "operation": "write",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.coreusergroup.row.write",
    "name": "User Write Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 99,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\ModelModel",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.model.row.create",
    "name": "Models Model Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 100,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CustomField",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.customfield.row.create",
    "name": "Custom Field Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 101,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\FormField",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.formfield.row.create",
    "name": "Form Field Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 102,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\EventHandler",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.eventhandler.row.create",
    "name": "Event Handler Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 103,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\InboundApi",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.inboundapi.row.create",
    "name": "Inbound Api Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 104,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Command",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.command.row.create",
    "name": "Command Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 105,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Iframe",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.iframe.row.create",
    "name": "Iframe Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 106,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\JavascriptLibrary",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.javascriptlibrary.row.create",
    "name": "Javascript Library Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 107,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Webhook",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.webhook.row.create",
    "name": "Webhook Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 108,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\ModelAssociation",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.modelassociation.row.create",
    "name": "Model Association Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 109,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Role",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.role.row.create",
    "name": "Role Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 110,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Permission",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.permission.row.create",
    "name": "Permission Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 111,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\SecurityPolicy",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.securitypolicy.row.create",
    "name": "Security Policy Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 112,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\PermissionPolicyAssociation",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.permissionpolicyassociation.row.create",
    "name": "Security Policy Association Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 113,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\RolePolicyAssociation",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.rolepolicyassociation.row.create",
    "name": "Role Policy Association Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 114,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CoreUser",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.coreuser.row.create",
    "name": "User Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 115,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CoreUserGroup",
    "operation": "create",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.coreusergroup.row.create",
    "name": "User Create Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 139,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\ModelModel",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.model.row.delete",
    "name": "Models Model Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 140,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CustomField",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.customfield.row.delete",
    "name": "Custom Field Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 141,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\FormField",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.formfield.row.delete",
    "name": "Form Field Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 142,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\EventHandler",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.eventhandler.row.delete",
    "name": "Event Handler Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 143,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\InboundApi",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.inboundapi.row.delete",
    "name": "Inbound Api Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 144,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Command",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.command.row.delete",
    "name": "Command Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 145,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Iframe",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.iframe.row.delete",
    "name": "Iframe Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 146,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\JavascriptLibrary",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.javascriptlibrary.row.delete",
    "name": "Javascript Library Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 147,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Webhook",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.webhook.row.delete",
    "name": "Webhook Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 148,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\ModelAssociation",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.modelassociation.row.delete",
    "name": "Model Association Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 149,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Role",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.role.row.delete",
    "name": "Role Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 150,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\Permission",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.permission.row.delete",
    "name": "Permission Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 151,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\SecurityPolicy",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.securitypolicy.row.delete",
    "name": "Security Policy Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 152,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\PermissionPolicyAssociation",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.permissionpolicyassociation.row.delete",
    "name": "Security Policy Association Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 153,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\RolePolicyAssociation",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.rolepolicyassociation.row.delete",
    "name": "Role Policy Association Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 154,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CoreUser",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.coreuser.row.delete",
    "name": "User Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  },
  {
    "id": 155,
    "created_at": "2019-12-20 14:15:39",
    "updated_at": "2019-12-20 14:15:39",
    "created_by_id": 1,
    "updated_by_id": 1,
    "plugin_id": 10,
    "model": "Demo\\Core\\Models\\CoreUserGroup",
    "operation": "delete",
    "columns": null,
    "condition": null,
    "code": "demo.core::models.coreusergroup.row.delete",
    "name": "User Delete Permission",
    "description": null,
    "active": true,
    "system": true,
    "admin_override": true
  }
]', true));
    }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
        Db::table('demo_core_permissions')->where('plugin_id', 10)->delete();
    }
}
