<?php
namespace Demo\Core\Seeds;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds Demo.Core d */
class SeedDemoCoreModels implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_models')->insert([
            [
                                                                            "id"=> 501,
                                                                                        "created_at"=>"2020-04-26 07:09:40",
                                                                                        "updated_at"=>"2020-04-26 07:09:40",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"List Action",
                                                                                        "model"=>"Demo\Core\Models\ListAction",
                                                                                        "controller"=>"Demo\Core\Controllers\ListActionController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=> 0,
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> 1
                            ] ,            [
                                                                            "id"=> 89,
                                                                                        "created_at"=>"2020-04-18 15:35:39",
                                                                                        "updated_at"=>"2020-04-18 15:35:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Audit Log",
                                                                                        "model"=>"Demo\Core\Models\AuditLog",
                                                                                        "controller"=>"Demo\Core\Controllers\AuditLogController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=> 0,
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 88,
                                                                                        "created_at"=>"2020-04-18 14:53:04",
                                                                                        "updated_at"=>"2020-04-18 15:36:42",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Model Model",
                                                                                        "model"=>"Demo\Core\Models\ModelModel",
                                                                                        "controller"=>"Demo\Core\Controllers\ModelController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=> 0,
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 87,
                                                                                        "created_at"=>"2020-04-13 14:06:29",
                                                                                        "updated_at"=>"2020-04-13 14:06:29",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Universal",
                                                                                        "model"=>"Demo\Core\Models\UniversalModel",
                                                                                        "controller"=>"Demo\Core\Controllers\UniversalController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=> 0,
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 20,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Notification Subscriber",
                                                                                        "model"=>"Demo\Notification\Models\NotificationSubscriber",
                                                                                        "controller"=>"Demo\Notification\Controllers\NotificationSubscriberController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 2,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Custom Field",
                                                                                        "model"=>"Demo\Core\Models\CustomField",
                                                                                        "controller"=>"Demo\Core\Controllers\CustomFieldController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 3,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Form Field",
                                                                                        "model"=>"Demo\Core\Models\FormField",
                                                                                        "controller"=>"Demo\Core\Controllers\FormFieldController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 4,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Event Handler",
                                                                                        "model"=>"Demo\Core\Models\EventHandler",
                                                                                        "controller"=>"Demo\Core\Controllers\EventHandlerController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 5,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Inbound Api",
                                                                                        "model"=>"Demo\Core\Models\InboundApi",
                                                                                        "controller"=>"Demo\Core\Controllers\InboundApiController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 6,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Command",
                                                                                        "model"=>"Demo\Core\Models\Command",
                                                                                        "controller"=>"Demo\Core\Controllers\CommandController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 7,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Iframe",
                                                                                        "model"=>"Demo\Core\Models\Iframe",
                                                                                        "controller"=>"Demo\Core\Controllers\IframeController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 8,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Javascript Library",
                                                                                        "model"=>"Demo\Core\Models\JavascriptLibrary",
                                                                                        "controller"=>"Demo\Core\Controllers\JavascriptLibraryController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 9,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Webhook",
                                                                                        "model"=>"Demo\Core\Models\Webhook",
                                                                                        "controller"=>"Demo\Core\Controllers\WebhookController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 10,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Model Association",
                                                                                        "model"=>"Demo\Core\Models\ModelAssociation",
                                                                                        "controller"=>"Demo\Core\Controllers\AssociationController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 12,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Permission",
                                                                                        "model"=>"Demo\Core\Models\Permission",
                                                                                        "controller"=>"Demo\Core\Controllers\PermissionController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 13,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Security Policy",
                                                                                        "model"=>"Demo\Core\Models\SecurityPolicy",
                                                                                        "controller"=>"Demo\Core\Controllers\SecurityPolicyController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 14,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Security Policy Association",
                                                                                        "model"=>"Demo\Core\Models\PermissionPolicyAssociation",
                                                                                        "controller"=>"Demo\Core\Controllers\PermissionPolicyAssociationController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 15,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Role Policy Association",
                                                                                        "model"=>"Demo\Core\Models\RolePolicyAssociation",
                                                                                        "controller"=>"Demo\Core\Controllers\RolePolicyAssociationController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 18,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Notification Channel",
                                                                                        "model"=>"Demo\Notification\Models\NotificationChannel",
                                                                                        "controller"=>"Demo\Notification\Controllers\NotificationChannelController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 19,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Notification",
                                                                                        "model"=>"Demo\Notification\Models\Notification",
                                                                                        "controller"=>"Demo\Notification\Controllers\NotificationController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 508,
                                                                                        "created_at"=>"2020-04-27 12:16:53",
                                                                                        "updated_at"=>"2020-05-08 08:13:16",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Role",
                                                                                        "model"=>"Demo\Core\Models\Role",
                                                                                        "controller"=>"Demo\Core\Controllers\RoleController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=> 0,
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 510,
                                                                                        "created_at"=>"2020-05-10 04:11:48",
                                                                                        "updated_at"=>"2020-05-10 04:11:48",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"users",
                                                                                        "model"=>"Demo\Core\Models\User",
                                                                                        "controller"=>"Demo\Core\Controllers\UserController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"*",
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 511,
                                                                                        "created_at"=>"2020-05-10 04:11:48",
                                                                                        "updated_at"=>"2020-05-10 04:11:48",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"case_priority",
                                                                                        "model"=>"Demo\Casemanager\Models\Casepriority",
                                                                                        "controller"=>"Demo\Casemanager\Controllers\CasepriorityController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"*",
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 512,
                                                                                        "created_at"=>"2020-05-10 04:11:48",
                                                                                        "updated_at"=>"2020-05-10 04:11:48",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"workflow_transitions",
                                                                                        "model"=>"Demo\Workflow\Models\WorkflowTransitions",
                                                                                        "controller"=>"Demo\Workflow\Controllers\WorkflowTransitionsController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"*",
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 513,
                                                                                        "created_at"=>"2020-05-10 04:11:48",
                                                                                        "updated_at"=>"2020-05-10 04:11:48",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"logs",
                                                                                        "model"=>"Demo\Notification\Models\NotificationLog",
                                                                                        "controller"=>"Demo\Notification\Controllers\NotificationLogController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"*",
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 514,
                                                                                        "created_at"=>"2020-05-10 04:11:48",
                                                                                        "updated_at"=>"2020-05-10 04:11:48",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"user_role_associations",
                                                                                        "model"=>"Demo\Core\Models\UserRoleAssociation",
                                                                                        "controller"=>"Demo\Core\Controllers\UserRoleAssociationController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"*",
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 515,
                                                                                        "created_at"=>"2020-05-10 04:11:48",
                                                                                        "updated_at"=>"2020-05-10 04:11:48",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"routing_rules",
                                                                                        "model"=>"Demo\Workflow\Models\QueueRoutingrule",
                                                                                        "controller"=>"Demo\Workflow\Controllers\QueueRoutingruleController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"*",
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 16,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"User",
                                                                                        "model"=>"Demo\Core\Models\CoreUser",
                                                                                        "controller"=>"Demo\Core\Controllers\UserController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 17,
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"User",
                                                                                        "model"=>"Demo\Core\Models\CoreUserGroup",
                                                                                        "controller"=>"Demo\Core\Controllers\UserGroupController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\" * \"]",
                                                                                        "description"=> null,
                                                                                        "attach_audited_by"=> 1,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 502,
                                                                                        "created_at"=>"2020-04-26 07:16:16",
                                                                                        "updated_at"=>"2020-04-26 07:16:16",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Form Action",
                                                                                        "model"=>"Demo\Core\Models\FormAction",
                                                                                        "controller"=>"Demo\Core\Controllers\FormActionController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=> 0,
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> 1
                            ] ,            [
                                                                            "id"=> 517,
                                                                                        "created_at"=>"2020-05-10 04:11:48",
                                                                                        "updated_at"=>"2020-05-10 04:11:48",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"groups",
                                                                                        "model"=>"Demo\Core\Models\UserGroup",
                                                                                        "controller"=>"Demo\Core\Controllers\UserGroupController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"*",
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 518,
                                                                                        "created_at"=>"2020-05-10 05:15:28",
                                                                                        "updated_at"=>"2020-05-10 05:15:28",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Navigation Role Association",
                                                                                        "model"=>"Demo\Core\Models\NavigationRoleAssociation",
                                                                                        "controller"=>"Demo\Core\Controllers\NavigationRoleAssociationController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=> 0,
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 524,
                                                                                        "created_at"=>"2020-05-26 14:00:24",
                                                                                        "updated_at"=>"2020-05-26 14:00:24",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Setting",
                                                                                        "model"=>"System\Models\Parameter",
                                                                                        "controller"=>"Demo\Core\Controllers\SettingController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=> 0,
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 509,
                                                                                        "created_at"=>"2020-05-09 11:25:29",
                                                                                        "updated_at"=>"2020-05-10 16:00:23",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Navigation",
                                                                                        "model"=>"Demo\Core\Models\Navigation",
                                                                                        "controller"=>"Demo\Core\Controllers\NavigationController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=>"[\"*\"]",
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ] ,            [
                                                                            "id"=> 519,
                                                                                        "created_at"=>"2020-05-16 05:56:51",
                                                                                        "updated_at"=>"2020-05-16 05:56:51",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"UI Page",
                                                                                        "model"=>"Demo\Core\Models\UiPage",
                                                                                        "controller"=>"Demo\Core\Controllers\UiPageController",
                                                                                        "plugin_id"=> 10,
                                                                                        "audit"=> false,
                                                                                        "record_history"=> false,
                                                                                        "audit_columns"=> 0,
                                                                                        "description"=> "",
                                                                                        "attach_audited_by"=> false,
                                                                                        "viewable"=> false
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_models')->where('plugin_id', 10)->delete();
            }
}
