<?php
namespace Demo\Core\Seeds;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds Demo.Core d */
class SeedDemoCoreSecurityPolicies implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_security_policies')->insert([
            [
                                                                            "id"=> 507,
                                                                                        "created_at"=>"2020-04-26 07:09:39",
                                                                                        "updated_at"=>"2020-04-26 07:09:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"List Action Policy",
                                                                                        "description"=>"Autogenerated policy for List Action",
                                                                                        "plugin_id"=> 2
                            ] ,            [
                                                                            "id"=> 512,
                                                                                        "created_at"=>"2020-04-26 07:16:15",
                                                                                        "updated_at"=>"2020-04-26 07:16:15",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Form Action Policy",
                                                                                        "description"=>"Autogenerated policy for Form Action",
                                                                                        "plugin_id"=> 2
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_security_policies')->where('plugin_id', 2)->delete();
            }
}
