<?php namespace Demo\Workflow\Models;

use Model;
use Backend\Models\User;
use October\Rain\Exception\ApplicationException;

/**
 * Model
 */
class WorkflowState extends Model
{
    use \October\Rain\Database\Traits\Validation;
    use \Demo\Core\Classes\Traits\ModelTrait;

    const START = '09dfd34e-0db5-49f3-96b2-23831d811a0b';
    const FINISH = '8c7e9158-b65c-437a-a5d9-4b975f7b6f51';
    /**
     * @var string The database table used by the model.
     */
    public $table = 'demo_workflow_workflow_states';
    public $incrementing = false;

    /**
     * @var array Validation rules
     */
    public $rules = [
        'name' => 'required',
        'code' => 'required',
        'active' => 'boolean',
        'application' => 'required',
    ];
    public $attachAuditedBy = true;

    public $belongsTo = [
        'created_by' => [User::class, 'key' => 'created_by_id'],
        'updated_by' => [User::class, 'key' => 'updated_by_id'],
        'application' => [\Demo\Core\Models\EngineApplication::class, 'key' => 'engine_application_id']
    ];

    protected function beforeUpdate()
    {
        if (in_array($this->id, [WorkflowState::START, WorkflowState::FINISH]) && !$this->active) {
            throw new ApplicationException('Can not deactivate system generated states');
        }
        parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    protected function beforeDelete()
    {
        if (in_array($this->id, [WorkflowState::START, WorkflowState::FINISH])) {
            throw new ApplicationException('Can not delete system generated states');
        }
        parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
