<?php


namespace Demo\Core\Tests;


use Backend\Models\User;
use Demo\Core\Models\InboundApi;
use PluginTestCase;
use BackendAuth;

class PluginTestSetup extends PluginTestCase
{
    const TEST_CONFIG = ['login-user' => 'admin'];

    public function setUser()
    {
        $loginuser = PluginTestSetup::TEST_CONFIG['login-user'];
        BackendAuth::setUser(User::where('login', $loginuser)->first());
    }

    public function assertAuditableFields($model)
    {
        if ($model->attachAuditedBy) {
            $this->assertNotEmpty($model->created_at);
            $this->assertNotEmpty($model->created_by_id);
            $this->assertNotEmpty($model->updated_at);
            $this->assertNotEmpty($model->updated_by_id);
        }
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setUser();

    }
}