<?php


namespace Demo\Core\Tests;


use Backend\Models\User;
use Demo\Core\Classes\Helpers\PluginConnection;
use Demo\Core\Models\InboundApi;
use PluginTestCase;
use BackendAuth;

class PluginTestSetup extends PluginTestCase
{

    public function setUser()
    {
        $loginuser = PluginConnection::getEnv('user');
        print 'Setting loggedin user to -> ' . $loginuser;
        BackendAuth::setUser(User::where('login', $loginuser)->first());
    }

    public function assertAuditableFields($model)
    {
        if ($model->attachAuditedBy) {
            $this->assertNotEmpty($model->created_at);
            $this->assertNotEmpty($model->created_by_id);
            $this->assertNotEmpty($model->updated_at);
            $this->assertNotEmpty($model->updated_by_id);
        }
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        // PluginConnection::reloadModels();
        $this->setUser();

    }
}