<?php
namespace Demo\Casemanager\Seeds;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds Demo.Casemanager d */
class SeedDemoCorePermissions implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_permissions')->insert([
            [
                                                                            "id"=>"35fce9b9-8b6a-4a92-a214-6d4e554f1e81",
                                                                                        "created_at"=>"2020-04-27 10:59:16",
                                                                                        "updated_at"=>"2020-04-27 10:59:16",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CasePriority",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.casemanager::models.casepriority.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Priority read Permission",
                                                                                        "description"=>"This is the system generated permission for Case Priority read",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"b4e3b6cb-ebb1-4fbc-bc65-f59a2008da61",
                                                                                        "created_at"=>"2020-04-27 10:59:16",
                                                                                        "updated_at"=>"2020-04-27 10:59:16",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CasePriority",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.casemanager::models.casepriority.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Priority write Permission",
                                                                                        "description"=>"This is the system generated permission for Case Priority write",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"58faebcc-6b97-4b46-9e9e-0070f1556837",
                                                                                        "created_at"=>"2020-04-27 10:59:16",
                                                                                        "updated_at"=>"2020-04-27 10:59:16",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CasePriority",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.casemanager::models.casepriority.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Priority create Permission",
                                                                                        "description"=>"This is the system generated permission for Case Priority create",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"50880924-3110-478c-b01b-63c5c456edeb",
                                                                                        "created_at"=>"2020-04-27 10:59:17",
                                                                                        "updated_at"=>"2020-04-27 10:59:17",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CasePriority",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.casemanager::models.casepriority.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Priority delete Permission",
                                                                                        "description"=>"This is the system generated permission for Case Priority delete",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"973f538e-62d3-4570-90d1-0310970e3046",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CaseModel",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> "",
                                                                                        "condition"=> "",
                                                                                        "code"=>"demo.casemanager::models.casemodel.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Model Read Permission",
                                                                                        "description"=> "",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"df0f2fe6-9528-421b-8462-81491b982d82",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CasePriority",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> "",
                                                                                        "condition"=> "",
                                                                                        "code"=>"demo.casemanager::models.casepriority.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Priority Read Permission",
                                                                                        "description"=> "",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"687046cf-9692-4292-ad35-efce1aaf42d4",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CaseModel",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> "",
                                                                                        "condition"=> "",
                                                                                        "code"=>"demo.casemanager::models.casemodel.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Model Write Permission",
                                                                                        "description"=> "",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"f20adac9-f180-4720-b892-b58cf18f3166",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CasePriority",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> "",
                                                                                        "condition"=> "",
                                                                                        "code"=>"demo.casemanager::models.casepriority.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Priority Write Permission",
                                                                                        "description"=> "",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"dab8870c-1ba8-4846-b9b7-00bbd39ec3a4",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CaseModel",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> "",
                                                                                        "condition"=> "",
                                                                                        "code"=>"demo.casemanager::models.casemodel.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Model Create Permission",
                                                                                        "description"=> "",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"167aea1d-751c-4064-b7b4-b7a9a7e474ac",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CasePriority",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> "",
                                                                                        "condition"=> "",
                                                                                        "code"=>"demo.casemanager::models.casepriority.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Priority Create Permission",
                                                                                        "description"=> "",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"36edd8af-c53b-4f2b-9fb7-461f741a7676",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CaseModel",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> "",
                                                                                        "condition"=> "",
                                                                                        "code"=>"demo.casemanager::models.casemodel.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Model Delete Permission",
                                                                                        "description"=> "",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"9662eafc-606b-4108-b60a-28554776a560",
                                                                                        "created_at"=>"2019-12-20 14:15:39",
                                                                                        "updated_at"=>"2019-12-20 14:15:39",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\CasePriority",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> "",
                                                                                        "condition"=> "",
                                                                                        "code"=>"demo.casemanager::models.casepriority.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Case Priority Delete Permission",
                                                                                        "description"=> "",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"b6ccd813-b2c9-4df1-961c-04df2031a3a9",
                                                                                        "created_at"=>"2020-04-27 11:51:21",
                                                                                        "updated_at"=>"2020-04-27 11:51:21",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\Project",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.casemanager::models.project.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Project read Permission",
                                                                                        "description"=>"This is the system generated permission for Project read",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"9dd592de-c8bf-4c60-ae3f-5b48a49ed314",
                                                                                        "created_at"=>"2020-04-27 11:51:21",
                                                                                        "updated_at"=>"2020-04-27 11:51:21",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\Project",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.casemanager::models.project.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Project write Permission",
                                                                                        "description"=>"This is the system generated permission for Project write",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"2fe02db1-77fd-43eb-9cb6-e1c84b44bf7b",
                                                                                        "created_at"=>"2020-04-27 11:51:21",
                                                                                        "updated_at"=>"2020-04-27 11:51:21",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\Project",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.casemanager::models.project.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Project create Permission",
                                                                                        "description"=>"This is the system generated permission for Project create",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=>"c17220cd-f6f5-4912-9dfd-5045a93604a9",
                                                                                        "created_at"=>"2020-04-27 11:51:21",
                                                                                        "updated_at"=>"2020-04-27 11:51:21",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "engine_application_id"=> "df07f9b4-26c1-40ca-ba1f-1b77b1692b83",
                                                                                        "model"=>"Demo\Casemanager\Models\Project",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.casemanager::models.project.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Project delete Permission",
                                                                                        "description"=>"This is the system generated permission for Project delete",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_permissions')->where('engine_application_id', 'df07f9b4-26c1-40ca-ba1f-1b77b1692b83')->delete();
            }
}
