<?php
namespace Demo\Notification\Seeds;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds Demo.Notification d */
class SeedDemoCorePermissions implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_permissions')->insert([
            [
                                                                            "id"=> 565,
                                                                                        "created_at"=>"2020-05-17 05:47:52",
                                                                                        "updated_at"=>"2020-05-17 05:47:52",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailLayout",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.maillayout.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Layouts read Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Layouts read",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 566,
                                                                                        "created_at"=>"2020-05-17 05:47:53",
                                                                                        "updated_at"=>"2020-05-17 05:47:53",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailLayout",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.maillayout.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Layouts write Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Layouts write",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 567,
                                                                                        "created_at"=>"2020-05-17 05:47:53",
                                                                                        "updated_at"=>"2020-05-17 05:47:53",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailLayout",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.maillayout.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Layouts create Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Layouts create",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 568,
                                                                                        "created_at"=>"2020-05-17 05:47:53",
                                                                                        "updated_at"=>"2020-05-17 05:47:53",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailLayout",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.maillayout.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Layouts delete Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Layouts delete",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 573,
                                                                                        "created_at"=>"2020-05-17 05:53:01",
                                                                                        "updated_at"=>"2020-05-17 05:53:01",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailTemplate",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailtemplate.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Templates read Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Templates read",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 574,
                                                                                        "created_at"=>"2020-05-17 05:53:01",
                                                                                        "updated_at"=>"2020-05-17 05:53:01",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailTemplate",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailtemplate.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Templates write Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Templates write",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 575,
                                                                                        "created_at"=>"2020-05-17 05:53:01",
                                                                                        "updated_at"=>"2020-05-17 05:53:01",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailTemplate",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailtemplate.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Templates create Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Templates create",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 576,
                                                                                        "created_at"=>"2020-05-17 05:53:01",
                                                                                        "updated_at"=>"2020-05-17 05:53:01",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailTemplate",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailtemplate.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Templates delete Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Templates delete",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 561,
                                                                                        "created_at"=>"2020-05-17 05:46:59",
                                                                                        "updated_at"=>"2020-05-17 05:46:59",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailBrandSetting",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailbrandsetting.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Brand Setting read Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Brand Setting read",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 562,
                                                                                        "created_at"=>"2020-05-17 05:46:59",
                                                                                        "updated_at"=>"2020-05-17 05:46:59",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailBrandSetting",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailbrandsetting.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Brand Setting write Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Brand Setting write",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 563,
                                                                                        "created_at"=>"2020-05-17 05:46:59",
                                                                                        "updated_at"=>"2020-05-17 05:46:59",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailBrandSetting",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailbrandsetting.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Brand Setting create Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Brand Setting create",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 564,
                                                                                        "created_at"=>"2020-05-17 05:46:59",
                                                                                        "updated_at"=>"2020-05-17 05:46:59",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailBrandSetting",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailbrandsetting.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Brand Setting delete Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Brand Setting delete",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 569,
                                                                                        "created_at"=>"2020-05-17 05:52:10",
                                                                                        "updated_at"=>"2020-05-17 05:52:10",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailPartial",
                                                                                        "operation"=>"read",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailpartial.row.read",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Partial read Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Partial read",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 570,
                                                                                        "created_at"=>"2020-05-17 05:52:10",
                                                                                        "updated_at"=>"2020-05-17 05:52:10",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailPartial",
                                                                                        "operation"=>"write",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailpartial.row.write",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Partial write Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Partial write",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 571,
                                                                                        "created_at"=>"2020-05-17 05:52:11",
                                                                                        "updated_at"=>"2020-05-17 05:52:11",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailPartial",
                                                                                        "operation"=>"create",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailpartial.row.create",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Partial create Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Partial create",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ] ,            [
                                                                            "id"=> 572,
                                                                                        "created_at"=>"2020-05-17 05:52:11",
                                                                                        "updated_at"=>"2020-05-17 05:52:11",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "plugin_id"=> 3,
                                                                                        "model"=>"Demo\Notification\Models\MailPartial",
                                                                                        "operation"=>"delete",
                                                                                        "columns"=> null,
                                                                                        "condition"=> null,
                                                                                        "code"=>"demo.notification::models.mailpartial.row.delete",
                                                                                        "admin_override"=> 1,
                                                                                        "name"=>"Mail Partial delete Permission",
                                                                                        "description"=>"This is the system generated permission for Mail Partial delete",
                                                                                        "active"=> 1,
                                                                                        "system"=> 1
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_permissions')->where('plugin_id', 3)->delete();
            }
}
