<?php
namespace Demo\Notification\Seeds;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds Demo.Notification d */
class SeedDemoCoreSecurityPolicies implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_security_policies')->insert([
            [
                                                                            "id"=>"17d879db-f891-432e-8621-758eaf89593f",
                                                                                        "created_at"=>"2020-05-17 05:46:59",
                                                                                        "updated_at"=>"2020-05-17 05:46:59",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Mail Brand Setting Policy",
                                                                                        "description"=>"Autogenerated policy for Mail Brand Setting",
                                                                                        "engine_application_id"=> "c79b3f36-a77a-4de9-a9f0-f890a99728ef"
                            ] ,            [
                                                                            "id"=>"c789ebf5-15b8-47fe-94b3-52a2b78c1397",
                                                                                        "created_at"=>"2020-05-17 05:52:10",
                                                                                        "updated_at"=>"2020-05-17 05:52:10",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Mail Partial Policy",
                                                                                        "description"=>"Autogenerated policy for Mail Partial",
                                                                                        "engine_application_id"=> "c79b3f36-a77a-4de9-a9f0-f890a99728ef"
                            ] ,            [
                                                                            "id"=>"ccb4059f-d21c-4e9a-9a33-ede9a46b3291",
                                                                                        "created_at"=>"2020-05-17 05:47:52",
                                                                                        "updated_at"=>"2020-05-17 05:47:52",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Mail Layouts Policy",
                                                                                        "description"=>"Autogenerated policy for Mail Layouts",
                                                                                        "engine_application_id"=> "c79b3f36-a77a-4de9-a9f0-f890a99728ef"
                            ] ,            [
                                                                            "id"=>"d1b96d4c-11d9-4450-bf3f-d6a387cecbc9",
                                                                                        "created_at"=>"2020-05-17 05:53:00",
                                                                                        "updated_at"=>"2020-05-17 05:53:00",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Mail Templates Policy",
                                                                                        "description"=>"Autogenerated policy for Mail Templates",
                                                                                        "engine_application_id"=> "c79b3f36-a77a-4de9-a9f0-f890a99728ef"
                            ] ,            [
                                                                            "id"=>"c359e680-e9c6-11ea-b144-25830ad29c16",
                                                                                        "created_at"=>"2020-08-29 07:10:47",
                                                                                        "updated_at"=>"2020-08-29 07:10:47",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Application Policy",
                                                                                        "description"=>"Autogenerated policy for Application",
                                                                                        "engine_application_id"=> "c79b3f36-a77a-4de9-a9f0-f890a99728ef"
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_security_policies')->where('engine_application_id', 'c79b3f36-a77a-4de9-a9f0-f890a99728ef')->delete();
            }
}
