<?php
namespace Demo\Notification\Seeds;

use Schema;
use Seeder;
use Demo\Core\Classes\Ifs\Seedable;
use Db;

/**Auto generated using cmd _: php artisan core:run-seeds Demo.Notification d */
class SeedDemoCoreSecurityPolicies implements Seedable
{
    /**This will be executed to install seeds*/
    public function install()
    {
            Db::table('demo_core_security_policies')->insert([
            [
                                                                            "id"=> 522,
                                                                                        "created_at"=>"2020-05-17 05:46:59",
                                                                                        "updated_at"=>"2020-05-17 05:46:59",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Mail Brand Setting Policy",
                                                                                        "description"=>"Autogenerated policy for Mail Brand Setting",
                                                                                        "plugin_id"=> 3
                            ] ,            [
                                                                            "id"=> 524,
                                                                                        "created_at"=>"2020-05-17 05:52:10",
                                                                                        "updated_at"=>"2020-05-17 05:52:10",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Mail Partial Policy",
                                                                                        "description"=>"Autogenerated policy for Mail Partial",
                                                                                        "plugin_id"=> 3
                            ] ,            [
                                                                            "id"=> 523,
                                                                                        "created_at"=>"2020-05-17 05:47:52",
                                                                                        "updated_at"=>"2020-05-17 05:47:52",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Mail Layouts Policy",
                                                                                        "description"=>"Autogenerated policy for Mail Layouts",
                                                                                        "plugin_id"=> 3
                            ] ,            [
                                                                            "id"=> 525,
                                                                                        "created_at"=>"2020-05-17 05:53:00",
                                                                                        "updated_at"=>"2020-05-17 05:53:00",
                                                                                        "created_by_id"=> 1,
                                                                                        "updated_by_id"=> 1,
                                                                                        "name"=>"Mail Templates Policy",
                                                                                        "description"=>"Autogenerated policy for Mail Templates",
                                                                                        "plugin_id"=> 3
                            ]             ]);
        }

    /**This will be executed to uninstall seeds*/
    public function uninstall()
    {
                    Db::table('demo_core_security_policies')->where('plugin_id', 3)->delete();
            }
}
